elec3609/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from welcomepage.views import *
from courses.views import *
from student.views import *
from news.views import *
from quiz import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^welcomepage', welcomepage),
    url(r'^homepage/', display_Course),
    url(r'^news/', display_news),
    url(r'^studentprofile/$',display_name),
    url(r'^subject/', include('subject.urls', namespace='question', app_name='subject')),

    url(r'^insert$', csrf_exempt(views.insert)),
    url(r'^quiz$', csrf_exempt(views.list)),
    url(r'^selectquiz/(?P<cid>\d+)/', csrf_exempt(views.get_all_quiz)),
    url(r'^score$',csrf_exempt(views.score)),
    url(r'^choose_to_add/(?P<cid>\d+)$',csrf_exempt(views.add_all_quiz)),
    url(r'^submit_answers$', csrf_exempt(views.check_answers)),
    url(r'^question_to_insert$', csrf_exempt(views.question_to_insert)),
]

quiz/urls.py
from django.conf.urls import url
from django.contrib import admin
from quiz import views

urlpatterns = [

]

subject/urls.py
from django.conf.urls import url, include

from subject import views
import subject
from django.views.decorators.csrf import csrf_exempt
urlpatterns = [
    #question detail display
    url(r'^(?P<subid>\d+)/(?P<qid>\d+)$', views.question_detail,
        name='question_detail'),
    # views of question
    url(r'^(?P<subid>\d+)$', views.question_list,name='question_list'),
    #dirction of like
    url(r'^like/', views.like),



]

subject/models.py
from django.db import models

# Create your models here.
from django.utils import timezone
from account.models import User
from student.models import *
from django.core.urlresolvers import reverse
from ckeditor.fields import *
#create manager to prepare for query function
class QuestionManager(models.Manager):
	def get_queryset(self):
		return super(QuestionManager, self).get_queryset().filter(status='published')
#create question data model
class Question(models.Model):
	STATUS_CHOICES = (('draft', 'Draft'), ('published', 'Published'),)
	Q_title = models.CharField(max_length=200)
	Q_des = RichTextField()
	create = models.DateTimeField(default=timezone.now)
	writer = models.ForeignKey(User, related_name='question_posts',null=True)
	course = models.ForeignKey(Subject_table,null=True)
	slug = models.SlugField(max_length=300, unique_for_date='create')
	Q_date = models.DateTimeField(auto_now_add=True)
	status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='published')
	objects = models.Manager()
	likes_num = models.IntegerField(default=0)
	published = QuestionManager()

	# order question with date
	class Meta:
		ordering = ('-create',)

	# the default human-readable representation of the object
	def __str__(self):
		return self.Q_title

	# def  get_absolute_url(self,User,Courses_table):
	# 	return reverse('question:question_detail',
	# 	args=[User.id,Courses_table.id,self.id])

	# create answer data model
class Answer(models.Model):
	ans = models.ForeignKey(Question, related_name='answers')
	title = models.CharField(max_length=50)
	content = RichTextField()
	A_date = models.DateTimeField(auto_now_add=True)
	update = models.DateTimeField(auto_now=True)
	allow = models.BooleanField(default=True)

	# order answer by created data
	class Meta:
		ordering = ('A_date',)

	# the default human-readable representation of the object
	def __str__(self):
		return 'Answer by {} on {}'.format(self.title, self.ans)

subject/views.py
from __future__ import unicode_literals
import datetime
from django.forms.models import model_to_dict
from django.core.serializers import serialize
import json
from django.shortcuts import render, render_to_response
from django.core import serializers
from django.shortcuts import render, get_object_or_404
from .models import *
from account.models import *
from courses.models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect
from .form import *
from django.db import models
from django.shortcuts import redirect
from django.views.decorators.csrf import *
from django.shortcuts import render
from django.template.context_processors import csrf
from django.http import HttpResponse
from student.models import *
# Create your views here.


def question_list(request,subid):
    user =get_object_or_404(User,id=request.user.id)

    request.session['cur_subject']=subid

    course= get_object_or_404(Subject_table,subject_id=subid)
    q_list = Question.objects.filter(course=subid)
    user =request.user
    # add question
    Qform = QuestionForm(request.POST or None)
    if Qform.is_valid():
        nquestion=Qform.save(commit=False)
        nquestion.writer=user
        nquestion.course=course
        nquestion.save()
    # paging
    paginator = Paginator(q_list, 4)
    page = request.GET.get('page')
    try:
        questions = paginator.page(page)
    except PageNotAnInteger:
        questions = paginator.page(1)
    except EmptyPage:
        questions = paginator.page(paginator.num_pages)



    return render(request, 'subject/subject.html', {'questions': questions,'user':user,'course':course,'Qform':Qform,'user':user})

def question_detail(request,subid,qid):
    global guid
    # get question id
    question = get_object_or_404(Question,id=qid)
    user =get_object_or_404(User,id=request.user.id)
    course= get_object_or_404(Subject_table,subject_id=subid)
    # add answer


    Aform = AnswerForm(request.POST or None)
    if Aform.is_valid():
        instance = Aform.save(commit=False)
        instance.ans = question
        instance.save()
    answers = question.answers.filter(allow=True)
    instance = None
    # paging according to subject
    q_list = Question.objects.filter(course=subid)
    paginator = Paginator(q_list, 4)
    page = request.GET.get('page')
    try:
        questions = paginator.page(page)
    except PageNotAnInteger:
        questions = paginator.page(1)
    except EmptyPage:
        questions = paginator.page(paginator.num_pages)

   #add question
    Qform = QuestionForm(request.POST or None)
    if Qform.is_valid():
        nquestion=Qform.save(commit=False)
        nquestion.writer=user
        nquestion.course=course
        if((nquestion.course!=None)and(nquestion.writer!=None)):
            nquestion.save()
    # return quesiton detail page.
    return render(request,
		'subject/details.html',
		{'question': question,
		'answers': answers,
		'new_answer': instance,
		'Aform': Aform,
         'questions': questions,
         'Qform': Qform,
         'user':user,
         'course':course,})


isLike = False
Nextq="a"

# like function
@csrf_exempt
def like(request):
    global  isLike
    qqid =request.POST.get('qqid')
    liken=int(request.POST.get('like_num'))
    q_list1 = Question.objects.filter(id=qqid)
    # if isLike == False:
    a = str(liken + 1)
    # isLike = True
    Question.objects.filter(id=qqid).update(likes_num=a)
#     elif isLike== True:
#         b = str(liken-1)
#         Question.objects.filter(id=qqid).update(likes_num=b)
#         isLike=False
# #


@csrf_exempt
def search(request):

    content = request.POST.get('content')
    questions = Question.objects.filter(course_id="1").filter(Q_title__icontains=content)
    qid_list = [];
    cid_list=[];
    for question in questions:
      qid_list.append(question.id)
      cid_list.append(question.course_id)
    # paginator = Paginator(questions, 4)
    # page = request.GET.get('page')
    # try:
    #     questions = paginator.page(page)
    # except PageNotAnInteger:
    #     questions = paginator.page(1)
    # except EmptyPage:
    #     questions = paginator.page(paginator.num_pages)
      serial =  serializers.serialize('json', questions.published.all())


    print(serial)
    return render_to_response('subject/details.html', {'q_list': json.dumps(questions)})



# @csrf_exempt
# def search(request):
#     global guid,gsubid,gqid
#     a=1
#     content = request.POST.get('content')
#     question =Question.objects.filter(course_id=a).filter(Q_title__icontains = content)
#
#     questionall = get_object_or_404(Question,id=gqid)
#     user =get_object_or_404(User,id=guid)
#     course= get_object_or_404(Courses_table,id=gsubid)
#
#     Aform = AnswerForm(request.POST or None)
#
#     if Aform.is_valid():
#         instance = Aform.save(commit=False)
#         instance.ans = question
#         instance.save()
#     answers = questionall.answers.filter(allow=True)
#     instance = None
#
#
#     q_list = Question.published.all()
#     paginator = Paginator(q_list, 4)
#     page = request.GET.get('page')
#     try:
#         questions = paginator.page(page)
#     except PageNotAnInteger:
#         questions = paginator.page(1)
#     except EmptyPage:
#         questions = paginator.page(paginator.num_pages)
#
#     Qform = QuestionForm(request.POST or None)
#     if Qform.is_valid():
#         nquestion=Qform.save(commit=False)
#         nquestion.writer=user
#         nquestion.course=course
#         if(nquestion.course!=None&nquestion.writer!=None):
#             nquestion.save()
#
#     return render(request,
#                   'subject/details.html',
#                   {'question': question,
#                    'answers': answers,
#                    'new_answer': instance,
#                    'Aform': Aform,
#                    'questions': questions,
#                    'Qform': Qform,
#                    'user': user,
#                    'course': course, })


# @csrf_exempt
# def search(request):
#     global guid,gsubid,gqid
#     a=1
#     content = request.POST.get('content')
#     question =Question.objects.filter(course_id=a).filter(Q_title__icontains = content)
#
#     return render(request,
#                   'subject/details.html',
#                   {'question': question,
#                    'answers': answers,
#                    'new_answer': instance,
#                    'Aform': Aform,
#                    'questions': questions,
#                    'Qform': Qform,
#                    'user': user,
#                    'course': course, })

subject/templates/subject/details.html
{% extends "base_s.html" %}

{% block title %}Question Details{% endblock %}
    <!--the title of the questions -->
{% block createQ %}
    <li><a href="" onclick="new_question();return false">New Question</a></li>
    {% if request.user.status == "Teacher" %}
        <li><a href="" onclick="makequiz();return false">Make Quiz</a></li>
    {% else %}
        <li><a href="" onclick="doquiz();return false">Do Quiz</a></li>
    {% endif %}
{% endblock %}
    <!--the add the answers for question  -->
{% block right-content %}
    <div id="add_answer" style="display: block">
        <h1>{{ question.Q_title }}</h1>
        <input type="hidden" id="qid" value={{ question.id }}>
        <input type="hidden" id="qlike" value={{ question.likes_num }}>

        <button type="button" onclick="likea()" class="btn btn-default"><span class="glyphicon glyphicon-star"
                                                                              aria-hidden="true"></span>{{ question.likes_num }}
        </button>

        <!--the display of the question  -->
        <p class="date">
            Published {{ question.create }} by {{ question.writer }}
        </p>
        {{ question.Q_des|linebreaks }}
        <hr>
        {% with answers.count as total_comments %}
            <h2>
                {{ total_answers }} answer {{ total_answers|pluralize }}
            </h2>
        {% endwith %}

            <!--the display of the answers  -->
        {% for answer in answers %}
            <div class="answer" style="display: block">
                <p class="info">{{ answer.A_date }}
                    Answer {{ forloop.counter }}
                </p>
                {{ answer.content|linebreaks }}
                <hr>
            </div>
        {% empty %}
            <p>There are no answers yet.</p>
        {% endfor %}
        {% if new_answer %}
            <h2>Your answer has been added.</h2>
        {% else %}
            <h2>Add a new answer :</h2>
            <form method='POST' action=''>{% csrf_token %}
                {{ Aform.as_p }}
                <button type="submit" class="btn btn-default navbar-btn" onsubmit="return checkSubmit();">Submit
                </button>
            </form>


        {% endif %}
    </div>
    <!-- create new question -->
    <div id="create_question" style='display: none'>

        <form method='POST' action=''>{% csrf_token %}


            <h2>Create New Question</h2>

            <hr>
            {{ Qform.as_p }}
            <button id="newquestion" type="submit" onclick="" class="btn btn-default navbar-btn">Create</button>
        </form>

    </div>


{% endblock %}


{% block left-content %}
        <!--the list of  questions -->
    <input id="course_id" type="hidden" value={{ course.subject_id}}>

    <h2> My Question</h2>s
    <hr>


    <hr>
    <div id="question">
        {% for question in questions %}
            <h2>

                <a href="{% url 'question:question_detail' subid=course.subject_id qid=question.id %}">{{ question.Q_title }}</a>

            </h2>

            <p class="date">
                Pulished {{ question.create }} by {{ question.writer }}
            </p>
            {{ question.Q_des|truncatewords:30|linebreaks }}
            <hr>

        {% endfor %}

    </div>
    {% include "pager.html" with page=questions %}


{% endblock %}

subject/templates/subject/subject.html
{% extends "base_s.html" %}
{% block createQ %}
    <!--the title of the questions -->
    <li><a href="" onclick="new_questionb();return false">New Question</a></li>
    {% if request.user.status == "Teacher" %}
        <li><a href="" onclick="makequiz();return false">Make Quiz</a></li>
    {% else %}
        <li><a href="" onclick="doquiz();return false">Do Quiz</a></li>
    {% endif %}
{% endblock %}

{% block title %} My Question{% endblock %}

{% block left-content %}
    <!--the list of  questions -->
    <h2> My Question</h2>
    <hr>

    <input id="course_id" type="hidden" value={{ course.subject_id }}>
    {% for question in questions %}
        <h2>
            <a href="{% url 'question:question_list' subid=course.subject_id %}/{{ question.id }}">{{ question.Q_title }}</a>
        </h2>
        <p class="date">
            Pulished {{ question.create }} by {{ question.writer }}
        </p>
        {{ question.Q_des|truncatewords:30|linebreaks }}
        <hr>

    {% endfor %}


    {% include "pager.html" with page=questions %}

{% endblock %}
{% block right-content %}
    <!-- create new question -->
    <div id="create_question1" style='display: none'>
        <form method='POST' action=''>{% csrf_token %}
            <h2>Create New Question</h2>
            <hr>
            {{ Qform.as_p }}

            <button type="submit" class="btn btn-default navbar-btn">Create</button>
        </form>
    </div>

{% endblock %}