elec3609/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from welcomepage.views import *
from courses.views import *
from student.views import *
from news.views import *
from quiz import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^welcomepage', welcomepage),
    url(r'^homepage/', display_Course),
    url(r'^news/', display_news),
    url(r'^studentprofile/$',display_name),
    url(r'^subject/', include('subject.urls', namespace='question', app_name='subject')),

    url(r'^insert$', csrf_exempt(views.insert)),
    url(r'^quiz$', csrf_exempt(views.list)),
    url(r'^selectquiz/(?P<cid>\d+)/', csrf_exempt(views.get_all_quiz)),
    url(r'^score$',csrf_exempt(views.score)),
    url(r'^choose_to_add/(?P<cid>\d+)$',csrf_exempt(views.add_all_quiz)),
    url(r'^submit_answers$', csrf_exempt(views.check_answers)),
    url(r'^question_to_insert$', csrf_exempt(views.question_to_insert)),
]

quiz/urls.py
from django.conf.urls import url
from django.contrib import admin
from quiz import views

urlpatterns = [

]

subject/urls.py
from django.conf.urls import url, include

from subject import views
import subject
from django.views.decorators.csrf import csrf_exempt
urlpatterns = [
    #question detail display
    url(r'^(?P<subid>\d+)/(?P<qid>\d+)$', views.question_detail,
        name='question_detail'),
    # views of question
    url(r'^(?P<subid>\d+)$', views.question_list,name='question_list'),
    #dirction of like
    url(r'^like/', views.like),



]

subject/models.py
from django.db import models

# Create your models here.
from django.utils import timezone
from account.models import User
from student.models import *
from django.core.urlresolvers import reverse
from ckeditor.fields import *
#create manager to prepare for query function
class QuestionManager(models.Manager):
	def get_queryset(self):
		return super(QuestionManager, self).get_queryset().filter(status='published')
#create question data model
class Question(models.Model):
	STATUS_CHOICES = (('draft', 'Draft'), ('published', 'Published'),)
	Q_title = models.CharField(max_length=200)
	Q_des = RichTextField()
	create = models.DateTimeField(default=timezone.now)
	writer = models.ForeignKey(User, related_name='question_posts',null=True)
	course = models.ForeignKey(Subject_table,null=True)
	slug = models.SlugField(max_length=300, unique_for_date='create')
	Q_date = models.DateTimeField(auto_now_add=True)
	status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='published')
	objects = models.Manager()
	likes_num = models.IntegerField(default=0)
	published = QuestionManager()

	# order question with date
	class Meta:
		ordering = ('-create',)

	# the default human-readable representation of the object
	def __str__(self):
		return self.Q_title

	# def  get_absolute_url(self,User,Courses_table):
	# 	return reverse('question:question_detail',
	# 	args=[User.id,Courses_table.id,self.id])

	# create answer data model
class Answer(models.Model):
	ans = models.ForeignKey(Question, related_name='answers')
	title = models.CharField(max_length=50)
	content = RichTextField()
	A_date = models.DateTimeField(auto_now_add=True)
	update = models.DateTimeField(auto_now=True)
	allow = models.BooleanField(default=True)

	# order answer by created data
	class Meta:
		ordering = ('A_date',)

	# the default human-readable representation of the object
	def __str__(self):
		return 'Answer by {} on {}'.format(self.title, self.ans)

subject/views.py
from __future__ import unicode_literals
import datetime
from django.forms.models import model_to_dict
from django.core.serializers import serialize
import json
from django.shortcuts import render, render_to_response
from django.core import serializers
from django.shortcuts import render, get_object_or_404
from .models import *
from account.models import *
from courses.models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect
from .form import *
from django.db import models
from django.shortcuts import redirect
from django.views.decorators.csrf import *
from django.shortcuts import render
from django.template.context_processors import csrf
from django.http import HttpResponse
from student.models import *
# Create your views here.


def question_list(request,subid):
    user =get_object_or_404(User,id=request.user.id)

    request.session['cur_subject']=subid

    course= get_object_or_404(Subject_table,subject_id=subid)
    q_list = Question.objects.filter(course=subid)
    user =request.user
    # add question
    Qform = QuestionForm(request.POST or None)
    if Qform.is_valid():
        nquestion=Qform.save(commit=False)
        nquestion.writer=user
        nquestion.course=course
        nquestion.save()
    # paging
    paginator = Paginator(q_list, 4)
    page = request.GET.get('page')
    try:
        questions = paginator.page(page)
    except PageNotAnInteger:
        questions = paginator.page(1)
    except EmptyPage:
        questions = paginator.page(paginator.num_pages)



    return render(request, 'subject/subject.html', {'questions': questions,'user':user,'course':course,'Qform':Qform,'user':user})

def question_detail(request,subid,qid):
    global guid
    # get question id
    question = get_object_or_404(Question,id=qid)
    user =get_object_or_404(User,id=request.user.id)
    course= get_object_or_404(Subject_table,subject_id=subid)
    # add answer


    Aform = AnswerForm(request.POST or None)
    if Aform.is_valid():
        instance = Aform.save(commit=False)
        instance.ans = question
        instance.save()
    answers = question.answers.filter(allow=True)
    instance = None
    # paging according to subject
    q_list = Question.objects.filter(course=subid)
    paginator = Paginator(q_list, 4)
    page = request.GET.get('page')
    try:
        questions = paginator.page(page)
    except PageNotAnInteger:
        questions = paginator.page(1)
    except EmptyPage:
        questions = paginator.page(paginator.num_pages)

   #add question
    Qform = QuestionForm(request.POST or None)
    if Qform.is_valid():
        nquestion=Qform.save(commit=False)
        nquestion.writer=user
        nquestion.course=course
        if((nquestion.course!=None)and(nquestion.writer!=None)):
            nquestion.save()
    # return quesiton detail page.
    return render(request,
		'subject/details.html',
		{'question': question,
		'answers': answers,
		'new_answer': instance,
		'Aform': Aform,
         'questions': questions,
         'Qform': Qform,
         'user':user,
         'course':course,})


isLike = False
Nextq="a"

# like function
@csrf_exempt
def like(request):
    global  isLike
    qqid =request.POST.get('qqid')
    liken=int(request.POST.get('like_num'))
    q_list1 = Question.objects.filter(id=qqid)
    # if isLike == False:
    a = str(liken + 1)
    # isLike = True
    Question.objects.filter(id=qqid).update(likes_num=a)
#     elif isLike== True:
#         b = str(liken-1)
#         Question.objects.filter(id=qqid).update(likes_num=b)
#         isLike=False
# #


@csrf_exempt
def search(request):

    content = request.POST.get('content')
    questions = Question.objects.filter(course_id="1").filter(Q_title__icontains=content)
    qid_list = [];
    cid_list=[];
    for question in questions:
      qid_list.append(question.id)
      cid_list.append(question.course_id)
    # paginator = Paginator(questions, 4)
    # page = request.GET.get('page')
    # try:
    #     questions = paginator.page(page)
    # except PageNotAnInteger:
    #     questions = paginator.page(1)
    # except EmptyPage:
    #     questions = paginator.page(paginator.num_pages)
      serial =  serializers.serialize('json', questions.published.all())


    print(serial)
    return render_to_response('subject/details.html', {'q_list': json.dumps(questions)})



# @csrf_exempt
# def search(request):
#     global guid,gsubid,gqid
#     a=1
#     content = request.POST.get('content')
#     question =Question.objects.filter(course_id=a).filter(Q_title__icontains = content)
#
#     questionall = get_object_or_404(Question,id=gqid)
#     user =get_object_or_404(User,id=guid)
#     course= get_object_or_404(Courses_table,id=gsubid)
#
#     Aform = AnswerForm(request.POST or None)
#
#     if Aform.is_valid():
#         instance = Aform.save(commit=False)
#         instance.ans = question
#         instance.save()
#     answers = questionall.answers.filter(allow=True)
#     instance = None
#
#
#     q_list = Question.published.all()
#     paginator = Paginator(q_list, 4)
#     page = request.GET.get('page')
#     try:
#         questions = paginator.page(page)
#     except PageNotAnInteger:
#         questions = paginator.page(1)
#     except EmptyPage:
#         questions = paginator.page(paginator.num_pages)
#
#     Qform = QuestionForm(request.POST or None)
#     if Qform.is_valid():
#         nquestion=Qform.save(commit=False)
#         nquestion.writer=user
#         nquestion.course=course
#         if(nquestion.course!=None&nquestion.writer!=None):
#             nquestion.save()
#
#     return render(request,
#                   'subject/details.html',
#                   {'question': question,
#                    'answers': answers,
#                    'new_answer': instance,
#                    'Aform': Aform,
#                    'questions': questions,
#                    'Qform': Qform,
#                    'user': user,
#                    'course': course, })


# @csrf_exempt
# def search(request):
#     global guid,gsubid,gqid
#     a=1
#     content = request.POST.get('content')
#     question =Question.objects.filter(course_id=a).filter(Q_title__icontains = content)
#
#     return render(request,
#                   'subject/details.html',
#                   {'question': question,
#                    'answers': answers,
#                    'new_answer': instance,
#                    'Aform': Aform,
#                    'questions': questions,
#                    'Qform': Qform,
#                    'user': user,
#                    'course': course, })

subject/templates/add_ans.html
<!DOCTYPE html>

<html lang="en-us">
<head>
    <title>Add answer | Django site admin</title>
    <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css"/>
    <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css"/>


    <script type="text/javascript" src="/admin/jsi18n/"></script>
    <script type="text/javascript" src="/static/admin/js/core.js"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
    <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
    <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
    <script type="text/javascript" src="/static/admin/js/actions.js"></script>
    <script type="text/javascript" src="/static/admin/js/urlify.js"></script>
    <script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>

    <meta name="robots" content="NONE,NOARCHIVE"/>
</head>


<body class=" app-subject model-answer change-form"
      data-admin-utc-offset="39600">

<!-- Container -->
<div id="container">


    <!-- Header -->
    <div id="header">
        <div id="branding">

            <h1 id="site-name"><a href="/admin/">Django administration</a></h1>

        </div>


        <div id="user-tools">

            Welcome,
            <strong>a</strong>.


            <a href="/">View site</a> /


            <a href="/admin/password_change/">Change password</a> /

            <a href="/admin/logout/">Log out</a>

        </div>


    </div>
    <!-- END Header -->

    <div class="breadcrumbs">
        <a href="/admin/">Home</a>
        &rsaquo; <a href="/admin/subject/">Subject</a>
        &rsaquo; <a href="/admin/subject/answer/">Answers</a>
        &rsaquo; Add answer
    </div>


    <!-- Content -->
    <div id="content" class="colM">

        <h1>Add answer</h1>
        <div id="content-main">


            <form enctype="multipart/form-data" action="" method="post" id="answer_form" novalidate><input type='hidden'
                                                                                                           name='csrfmiddlewaretoken'
                                                                                                           value='3IGHnKzd5ZPSGjyHOSpbBKjfSsBMEoki'/>
                <div>


                    <fieldset class="module aligned ">


                        <div class="form-row field-ans">


                            <div>


                                <label class="required" for="id_ans">Ans:</label>


                                <div class="related-widget-wrapper">
                                    <select id="id_ans" name="ans">
                                        <option value="" selected="selected">---------</option>
                                        <option value="1">why?</option>
                                    </select>


                                    <a class="related-widget-wrapper-link change-related" id="change_id_ans"
                                       data-href-template="/admin/subject/question/__fk__/change/?_to_field=id&amp;_popup=1"
                                       title="Change selected question">
                                        <img src="/static/admin/img/icon-changelink.svg" alt="Change"/>
                                    </a>


                                    <a class="related-widget-wrapper-link add-related" id="add_id_ans"
                                       href="/admin/subject/question/add/?_to_field=id&amp;_popup=1"
                                       title="Add another question">
                                        <img src="/static/admin/img/icon-addlink.svg" alt="Add"/>
                                    </a>


                                </div>


                            </div>

                        </div>

                        <div class="form-row field-name">


                            <div>


                                <label class="required" for="id_name">Name:</label>

                                <input class="vTextField" id="id_name" maxlength="50" name="name" type="text"/>


                            </div>

                        </div>

                        <div class="form-row field-content">


                            <div>


                                <label class="required" for="id_content">Content:</label>

                                <textarea class="vLargeTextField" cols="40" id="id_content" name="content" rows="10">
</textarea>


                            </div>

                        </div>

                        <div class="form-row field-allow">


                            <div class="checkbox-row">


                                <input checked="checked" id="id_allow" name="allow" type="checkbox"/><label
                                    class="vCheckboxLabel" for="id_allow">Allow</label>


                            </div>

                        </div>

                    </fieldset>


                    <div class="submit-row">
                        <input type="submit" value="Save" class="default" name="_save"/>


                        <input type="submit" value="Save and add another" name="_addanother"/>
                        <input type="submit" value="Save and continue editing" name="_continue"/>
                    </div>


                    <script type="text/javascript">
                        (function ($) {
                            $(document).ready(function () {
                                $('.add-another').click(function (e) {
                                    e.preventDefault();
                                    var event = $.Event('django:add-another-related');
                                    $(this).trigger(event);
                                    if (!event.isDefaultPrevented()) {
                                        showAddAnotherPopup(this);
                                    }
                                });


                                $('form#answer_form :input:visible:enabled:first').focus()

                            });
                        })(django.jQuery);
                    </script>


                    <script type="text/javascript">
                        (function ($) {
                            var field;


                        })(django.jQuery);
                    </script>


                </div>
            </form>
        </div>


        <br class="clear"/>
    </div>
    <!-- END Content -->

    <div id="footer"></div>
</div>
<!-- END Container -->

</body>
</html>

subject/templates/base_s.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %} </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Starter Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <script src="/static/js/subject.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/
jquery.min.js"></script>
    <script src=" http://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.
cookie.min.js "></script>
    <script>
        var csrftoken = $.cookie('csrftoken');

        function csrfSafeMethod(method) {
// these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
        $(document).ready(function () {
            {% block domready %}
            {% endblock %}
        });
    </script>
    <!-- Custom styles for this template -->


    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">StudyGo</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="http://127.0.0.1:8000/homepage">Homepage</a></li>

                  {% block createQ %}
                    {% endblock %}
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>


<div style="padding-top: 40px;">


    <h1 class="page-header" align="center">{% block page-header %}Disscussion Board{% endblock %}</h1>

    <!--the left part of the question  -->
    <div class="panel panel-default" id="left_panel"
         style="float: left;  margin-left: 15%; width: 300px; height: 720px;">
        <div class="panel-heading">
            <h2 class="panel-title">Question List</h2>
        </div>
        <div id="q_list"   class="panel-body">
            {% block left-content %}
            {% endblock %}
        </div>
    </div>
        <!--the right part of the question  -->
    <div id="right_panel" style="float: left; margin-left: 5%; width: 700px;">
        {% block right-content %}

        {% endblock %}

    </div>
</div>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<!--use the bootstrap -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script language="JavaScript" type="text/javascript" src="/static/js/jquery-1.7.2.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/
jquery.min.js"></script>


</body>
</html>

subject/templates/pager.html
<div class="pager">
<span class="step-links">
<!--use paginator to make mutipages display-->

{% if page.has_previous %}
<a href="?page={{ page.previous_page_number }}">Previous</a>
{% endif %}
<span class="current">
Page {{ page.number }} of {{ page.paginator.num_pages }}.
</span>
{% if page.has_next %}
<a href="?page={{ page.next_page_number }}">Next</a>
{% endif %}
</span>
</div>